defaults:
  working_directory: ~/workspace
version: 2.1
orbs:
  gradle: circleci/gradle@2.2.0
  artifactory: circleci/artifactory@1.0.0
executors:
  gradle-executor:
    docker:
      - image: circleci/openjdk
aliases:
  - &create-directory
    run:
      name: create directory
      command: |
        mkdir -p artifacts
jobs:
  build:
    working_directory: ~/repo
    executor: gradle-executor
    steps:
      - checkout
      - *create-directory
      - run:
          name: gradle build
          command: |
            ./gradlew build && cp -r build artifacts/build && ls -lrth artifacts && ls -lrth artifacts/build
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts
workflows:
  checkout-build-test:
    jobs:
      - gradle/test
      - build
      - artifactory/docker-publish:
          requires:
            - build
          docker-registry: circlecirepo.jfrog.io
          docker-steps:
            - run: docker build -t spingboot-docker .
          docker-tag: >-
            circlecirepo.jfrog.io/docker/spingboot-docker:1.0-${CIRCLE_BUILD_NUM}
          name: Docker Publish Custom Build
          repository: docker