version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/sandeebh/springboot-with-docker/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
orbs:
   gradle: circleci/gradle@2.2.0
   docker: circleci/docker@2.0.1


jobs:
  pco-circleci:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!
          ls -ltra
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          image: poc-springboot 
          lint-dockerfile: false

workflows:
  my-custom-workflow:
    jobs:
      -  pco-circleci
      -  example-job