version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/sandeebh/springboot-with-docker/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
orbs:
   gradle: circleci/gradle@2.2.0

jobs:
  pco-circleci:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!

workflows:
  my-custom-workflow:
    jobs:
      - pco-circleci
      - gradle/run:
            app_src_directory: src 
            command: docker build 