defaults:
  working_directory: ~/workspace
version: 2.1
orbs:
  gradle: circleci/gradle@2.2.0
  artifactory: circleci/artifactory@1.0.0
executors:
  gradle-executor:
    docker:
      - image: circleci/openjdk
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
aliases:
  - &create-directory
    run:
      name: create directory
      command: |
        mkdir -p artifacts
jobs:
  build:
    working_directory: ~/repo
    executor: gradle-executor
    steps:
      - checkout
      - *create-directory
      - run:
          name: gradle build
          command: |
            ./gradlew build && cp -r build artifacts/build && ls -lrth artifacts && ls -lrth artifacts/build
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts
  publish-to-artifactory-hub:
    executor: docker-publisher
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - setup_remote_docker
      - run: pwd && ls -lrth
      - run: docker login "${ARTIFACTORY_URL}" -u "${ARTIFACTORY_USER}" -p "${ARTIFACTORY_PASSWORD}"
      - run: docker build -t springboot-docker .
      - run:
          name: Tag and push to artifactory hub
          command:
            docker tag springboot-docker circlecirepo.jfrog.io/docker/spingboot-docker:1.0-${CIRCLE_BUILD_NUM}


workflows:
  checkout-build-test:
    jobs:
      - gradle/test
      - build
      - publish-to-artifactory-hub:
          requires:
            - build
