defaults:
  working_directory: ~/workspace
version: 2.1
orbs:
  gradle: circleci/gradle@2.2.0
  artifactory: circleci/artifactory@1.0.0
  kubernetes: circleci/kubernetes@1.0.0
executors:
  gradle-executor:
    docker:
      - image: circleci/openjdk
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
  helm:
    docker:
      - image: sibipro/sibi-helm:0.2
aliases:
  - &create-directory
    run:
      name: create directory
      command: |
        mkdir -p artifacts
  - &get-helmchart-version
    run:
      name: get the helm-chart version
      command: |
        export helmversion=$(helm show chart kubernetes/springapp | grep version | cut -d: -f 2 | tr -d ' ')
jobs:
  build:
    working_directory: ~/repo
    executor: gradle-executor
    steps:
      - checkout
      - *create-directory
      - run:
          name: gradle build
          command: |
            ./gradlew build && cp -r build artifacts/build && ls -lrth artifacts && ls -lrth artifacts/build
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts
  publish-to-artifactory-hub:
    executor: docker-publisher
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - setup_remote_docker
      - run: pwd && ls -lrth
      - run: docker build -t springboot-docker .
  
workflows:
  checkout-build-test:
    jobs:
      - build
      - publish-to-artifactory-hub:
          requires:
            - build

