defaults:
  working_directory: ~/workspace
version: 2.1
orbs:
  gradle: circleci/gradle@2.2.0
  artifactory: circleci/artifactory@1.0.0
executors:
  gradle-executor:
    docker:
      - image: circleci/openjdk
jobs:
  build:
    working_directory: /tmp
    executor: gradle-executor
    steps:
      - checkout
      - run:
          name: gradle build
          command: |
            ./gradlew build
      - store_artifacts:
          path: /tmp/build/
workflows:
  checkout-build-test:
    jobs:
      - gradle/test
      - build
      - artifactory/docker-publish:
          requires:
            - gradle/test
          docker-registry: circlecirepo.jfrog.io
          docker-steps:
            - run: docker build -t spingboot-docker .
          docker-tag: >-
            circlecirepo.jfrog.io/docker/spingboot-docker:1.0-${CIRCLE_BUILD_NUM}
          name: Docker Publish Custom Build
          repository: docker